services:
  api:
    container_name: api
    image: crafting-simulator:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
  angular:
    container_name: angular
    image: node:22.12.0
    expose:
      - "4200"
    ports:
      - "4200:4200"
    working_dir: /angular
    volumes:
      - type: bind
        source: ./angular/public
        target: /angular/public
      - type: bind
        source: ./angular/src
        target: /angular/src
      - type: bind
        source: ./angular/angular.json
        target: /angular/angular.json
      - type: bind
        source: ./angular/package.json
        target: /angular/package.json
      - type: bind
        source: ./angular/package-lock.json
        target: /angular/package-lock.json
      - type: bind
        source: ./angular/tsconfig.app.json
        target: /angular/tsconfig.app.json
      - type: bind
        source: ./angular/tsconfig.json
        target: /angular/tsconfig.json
      - type: bind
        source: ./angular/tsconfig.spec.json
        target: /angular/tsconfig.spec.json
      - type: bind
        source: ./angular/proxy.conf.json
        target: /angular/proxy.conf.json
    command: sh -c "npm install ; npm run start -- --host '0.0.0.0' --poll=1000"