services:
  api:
    container_name: api
    image: sbtscala/scala-sbt:amazoncorretto-al2023-21.0.5_1.10.6_3.6.2
    platform: linux/amd64
    expose:
      - "8080"
    ports:
      - "8080:8080"
    working_dir: /api
    volumes:
      - type: bind
        source: ./api/project/build.properties
        target: /api/project/build.properties
        read_only: true
      - type: bind
        source: ./api/project/plugins.sbt
        target: /api/project/plugins.sbt
        read_only: true
      - type: bind
        source: ./api/src
        target: /api/src
        read_only: true
      - type: bind
        source: ./api/build.sbt
        target: /api/build.sbt
        read_only: true
    command: sbt run
  angular:
    container_name: angular
    image: node:22.12.0
    expose:
      - "4200"
    ports:
      - "4200:4200"
    working_dir: /angular
    volumes:
      - type: bind
        source: ./angular/public
        target: /angular/public
        read_only: true
      - type: bind
        source: ./angular/src
        target: /angular/src
        read_only: true
      - type: bind
        source: ./angular/angular.json
        target: /angular/angular.json
        read_only: true
      - type: bind
        source: ./angular/package.json
        target: /angular/package.json
        read_only: true
      - type: bind
        source: ./angular/package-lock.json
        target: /angular/package-lock.json
        read_only: true
      - type: bind
        source: ./angular/tsconfig.app.json
        target: /angular/tsconfig.app.json
        read_only: true
      - type: bind
        source: ./angular/tsconfig.json
        target: /angular/tsconfig.json
        read_only: true
      - type: bind
        source: ./angular/tsconfig.spec.json
        target: /angular/tsconfig.spec.json
        read_only: true
      - type: bind
        source: ./angular/proxy.conf.json
        target: /angular/proxy.conf.json
        read_only: true
    command: sh -c "npm install ; npm run start -- --host '0.0.0.0' --poll=1000"
  db:
    container_name: db
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  flyway:
    container_name: flyway
    image: flyway/flyway:11-alpine
    volumes:
      - type: bind
        source: ./flyway/db/migration
        target: /flyway/db/migration
        read_only: true
      - type: bind
        source: ./flyway/conf
        target: /flyway/conf
        read_only: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    tty: true
    profiles:
      - tools
