name: CI
on:
  pull_request:
  workflow_dispatch:
permissions:
  checks: write
  pull-requests: write
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: fetch history
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch --depth=$(( ${{github.event.pull_request.commits}} + 1 )) origin ${{github.event.pull_request.head.ref}}:refs/remotes/origin/${{github.event.pull_request.head.ref}}
          echo BASE_REF=$(git rev-list --reverse remotes/origin/${{github.event.pull_request.head.ref}} | head -1) >> $GITHUB_ENV
      - name: scalafmtCheckAll
        working-directory: api
        run: sbt scalafmtCheckAll
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: run test
        working-directory: api
        run: sbt test
      - uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          summary: true
          detailed_summary: true