name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - name: run test
        working-directory: api
        run: sbt test