name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: commits+1
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - name: show
        run: |
          ls -a
          echo ""
          git branch -a
      - name: scalafmtCheckAll
        working-directory: api
        run: sbt scalafmtCheckAll
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - name: clone base branch
        run: git fetch origin master
      - name: run test
        working-directory: api
        run: sbt test