name: CI
on:
  pull_request:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - name: fetch history
        run: |
          git fetch --depth=$(( ${{github.event.pull_request.commits}} + 1 )) origin ${{github.event.pull_request.head.ref}}
          echo ""
          git rev-list --reverse HEAD
          echo ""
          git log
          echo ""
          echo BASE_REF=$(git rev-list --reverse HEAD | head -1) >> $GITHUB_ENV
      - name: scalafmtCheckAll
        working-directory: api
        run: sbt scalafmtCheckAll
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - name: clone base branch
        run: git fetch origin master
      - name: run test
        working-directory: api
        run: sbt test