name: sample.yml
on:
  workflow_dispatch:

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1"
      - name: step2
        run: echo "step2"

  ls_sample:
    runs-on: ubuntu-latest
    steps:
      - name: ls -al
        run: ls -al
      - name: pwd
        run: pwd
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ls -al
        run: ls -al
      - name: pwd
        run: pwd